[package]
name = "destream"
version = "0.1.1"
authors = ["haydnv"]
edition = "2018"
license = "Apache-2.0"
description = "Library for async steam (de)serialization"
repository = "http://github.com/haydnv/destream"
readme = "README.md"

categories = ["asynchronous", "encoding", "parsing", "rust-patterns"]
keywords = ["json", "stream", "streaming", "serialize", "deserialize"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
serde = "1.0"
